allowBuilds:
  '@reown/appkit': false
  '@stellar/stellar-sdk': false
  blake-hash: false
  bufferutil: set this to true or false
  keccak: set this to true or false
  protobufjs: false
  secp256k1: false
  tiny-secp256k1: false
  usb: false
  utf-8-validate: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
